/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/L39ONFFHsKO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Badge } from "@/components/ui/badge";
import Image from "next/image";


/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function UtopiaHero() {
  return (
    <section className="w-full md:py-12 md:px-12 bg-pink-500 rounded-2xl">
      <div className="container px-4 md:px-6">
        <div className="grid gap-6 lg:grid-cols-[1fr_1fr] xl:grid-cols-[1.5fr_1fr]">
          <div className="space-y-4">
            <p><Badge variant="default">for Girls</Badge> <span className="text-xs text-pink-400">The boy version is coming in the next weeks!</span></p>
            <h1 className="drop-shadow-lg drop-shadow-slate-800/60 text-slate-100 text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">
            Try any hairstyle without haircut
            </h1>
            <p className="max-w-[500px] text-pink-100 md:text-xl">
            Upload some photo of yourself and try lots of different hairstyles and hair colors.
            </p>

            <h1 className="drop-shadow-lg drop-shadow-slate-800/60 text-slate-100 text-4xl font-bold tracking-tight sm:text-5xl md:text-7xl lg:text-9xl">30</h1>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Image
              className="rounded-xl object-cover"
              height="500"
              alt="hello"
              src="/v1.jpg"
              style={{
                aspectRatio: "400/500",
                objectFit: "cover",
              }}
              width="400"
            />
            <Image
              className="rounded-xl object-cover"
              height="512"
              alt="hello"
              src="/v2.jpg"
              style={{
                aspectRatio: "512/512",
                objectFit: "cover",
              }}
              width="512"
            />
            <Image
              className="rounded-xl object-cover"
              height="500"
              alt="hello"
              src="/v4.jpg"
              style={{
                aspectRatio: "400/500",
                objectFit: "cover",
              }}
              width="400"
            />
          </div>
        </div>
      </div>
    </section>
  )
}
